name: ci
on:
  push:

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Format Lua files
        run: |
          curl -O -L https://github.com/JohnnyMorganz/StyLua/releases/download/v0.17.1/stylua-linux-x86_64.zip
          unzip stylua-linux-x86_64.zip
          chmod +x stylua
          ./stylua .
          rm stylua stylua-linux-x86_64.zip

      - name: Format Markdown files
        run: |
          npm install -g prettier
          prettier --write "**/*.md"
          
      - name: Commit files
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -a -m "style: format files [action]"; git push origin HEAD:${GITHUB_REF})
