name: Stylua Action

on:
  push:
    paths:
      - '**.lua'
    branches:
      - main
  pull_request:
    paths:
      - '**.lua'
    branches:
      - main

jobs:
  stylua_job:
    runs-on: macos-latest

    permissions:
      actions: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install Stylua
        run: brew install stylua

      - name: Format Lua files
        run: stylua .
        
      - name: Commit files
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -a -m "style: format Lua files [action]"; git push origin HEAD:${GITHUB_REF})
